### ISSUE TITLE
Usage of logger over printing debug statements

### ISSUE THREAD

**Issue by olivierobert** [rashikzaman/search-scrapper#3]
The package `scheduler` widely makes use of debugging practices that would make sense locally but less so in a production environment 😅  . Mainly it is about the usage of `fmt.Println`:

```
fmt.Println("Cannot read user agents file", userAgents)
```

How about using `Logger` instead?

**Comment by rashikzaman** [comment]
It is indeed a bad practice to use standard output in production. I've initially installed `logurs` as logger package to work with but then I got carried away doing a lot of `Println` for local purpose :(. I'll work on that and make sure debug log are turned off in production.
